from __future__ import annotations

from pathlib import Path
from typing import Protocol

from gpubox._models import Account, Instance, LaunchSpec, Offer, OfferQuery


class GpuCloud(Protocol):
    def account(self) -> Account: ...

    def list_offers(self, query: OfferQuery | None = None) -> list[Offer]: ...

    def create(self, offer_id: str, spec: LaunchSpec) -> str: ...

    def destroy(self, instance_id: str) -> None: ...

    def status(self, instance_id: str) -> Instance: ...

    def find(self, label: str) -> Instance | None: ...

    def run(self, instance_id: str, command: str) -> str: ...

    def upload(self, instance_id: str, local: Path, remote: str) -> None: ...

    def download(self, instance_id: str, remote: str, local: Path) -> None: ...

    def logs(self, instance_id: str) -> str: ...


StudioCloud = GpuCloud
